name: feature
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  flutter_tts: ^3.8.5
  cupertino_icons: ^1.0.8
  flutter_sound: ^9.28.0
  permission_handler: ^12.0.0+1
  path_provider: ^2.1.5
  intl: ^0.20.2
  lottie: ^3.3.1
  firebase_core: ^3.13.1
  firebase_auth: ^5.5.4
  cloud_firestore: ^5.6.8
  firebase_storage: ^12.4.6
  image_picker: ^1.1.2
  uuid: ^4.5.1
  cached_network_image: ^3.4.1
  location: ^8.0.0
  url_launcher: ^6.3.1
  shared_preferences: ^2.5.3
  android_intent_plus: ^5.3.0
  geolocator: ^14.0.1
  flutter_staggered_animations: ^1.1.1
  video_player: ^2.10.0
  chewie: ^1.11.3
  # telephony: ^0.2.0
  #firebase_core: ^3.14.0
 

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icons/app_icon.png"

flutter:
  uses-material-design: true

  assets:
    - assets/image/
    - assets/icons/app_icon.png
    - assets/videos/
   